---
title       : WiFi Latency
subtitle    : A Shiny App for evaluating a Sensor Network
author      : K. Pavelock
job         : Developing Data Products Coursera Class Project
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]       # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## WiFi Latency - Introduction

     Purpose: "To evaluate WiFi Latency for a sensor network based on several network parameters"  


### Network parameters
     - surveillance area
     - network hub range
     - wifi throughput
     - message size
     - number of major network transactions


### Selectable parameters       
     - Surveillance area (feet); "slider bar (60 - 5280*2)"       
     - Network node range (feet); "slider bar (25 - 200)"
     - WiFi throughput speed (Mbps); "slider bar (30 - 100)"

--- 

## WiFi Latency - Notes/Assumptions

- Average building area is 760 feet; Average area for a small city is 2 miles
- WiFi throughput for for 802.11n is 40-50 Mbps. From http://www.speedguide.net/faq/
- Message sizes (kilobytes-KB): small-50KB, medium-500KB, large-5000KB
- Requires 3 sensors per node; Alert Sensor with two Confirming Sensors
- Required main Network Messaging Transactions

     - Sensor discovery initiation via a status request;
     - Sensor discovery response via a status message;
     - Sensor(s) alert via alert message;
     - Detailed detection data request;
     - Detailed detection data transmittal;
     - Additional detailed detection data request;

---

## WiFi Latency - Formula

Network Processing Time (NP) is measured as Network Delay. 

Total Network Processing time $ NP_T $ is the sum of all NPs for each transaction:

$$ NP_T = \sum_{t=1}^n NP_t $$
$ n $ is the number of main transactions and $ NP_t $ is the network processing time for one major transaction:

$$ NP_t = NL * \left( d_r + d_p + d_c \right) $$
$ NL $ is the number of nodes (network routers + 1)
- Transmission Delay $ d_r $ average message size /Rate (WiFi Speed)
- Propagation Delay $ d_p $ distance/wave propagation speed. WiFi wave propagation speed = speed of light (186,000 miles per second)
- Processing Delay $ d_c $  time for routers to process packet headers.  This is negligible (set to 0)

---

## WiFi Latency - Outputs

A graph (plot) is displayed showing the latency versus number of sensors.  Calculated values are displayed as text labels:  Number of sensors, Surveillance area (Distance), and Latency.  The sample plot below is a replica from the Shiny App with WiFi speed of 45 Mbps and 100 ft hub range.
- Try it for yourself.  My WiFi Latency App is deployed at https://kathpave.shinyapps.io/Shiny/
```{r echo=FALSE}
dist.data <- seq(60,5280*2, 100) #min = 60, max = 5280*2, step = 100
#Transmission Delay 
#Message Size (KB)
Msg.data <- c(50,500,5000)
MsgMB <- Msg.data * 0.001 #convert to MB
sm<-1 #small message index
med <- 2 #medium message index
lg <- 3 #large message index
wifiMBps <- 45 * 0.125 #convert bits to Bytes
dtrans <- (MsgMB/wifiMBps) * 1000 #convert seconds to ms
#Propagation Delay
speedOfLight <- 186000 * 5280 # convert to feet per second
dprop <- (dist.data/speedOfLight) * 1000 # convert to ms
#Processing Delay
dproc <- 0 #time it takes routers to process packet headers (negligible)
#number of routers 
Hubs <- 100 #node range in feet 
NL <- round(dist.data/Hubs,0) + 1 # the number of nodes we need
numSensors <- (NL-1)*3 #sensors per node
# calculate Network Delay for each main transaction
NP1 <- NL * (dtrans[sm] + dprop + dproc) #Sensor Discovery (small message)
NP2 <- NL * (dtrans[med] + dprop + dproc) #Sensor Health Status (medium)
NP3 <- NP1 # Sensor alerts (small message)
NP4 <- NP1 # Request data from Sensors (small message)
NP5 <- NL * (dtrans[lg] + dprop + dproc) #Sensor data (large message)
NP6 <- NP1 # Request additional data from Sensors (small message)
Dtotal <- NP1 + NP2 + NP3 + NP4 + NP5 + NP6
currentDistance <- 760
index <- match(currentDistance,dist.data) #index for selected distance
par(fig=c(0, 1, .2, .8)) # make the plot fit on the page
plot(numSensors,Dtotal/1000, xlab='# Sensors', 
     ylab="Latency (seconds)", col='lightblue',
     main='Sensor System WiFi Latency')
lines(c(numSensors[index],numSensors[index]), c(0,300),
      col="blue",lwd=3)
#calculate placement of text labels
yTextValue <- round(mean(Dtotal/1000),0)
xTextValue <- round(max(numSensors)*0.8,0)
# display some parameters
text(xTextValue, yTextValue+10, paste("# Sensors = ", numSensors[index]))
text(xTextValue,yTextValue, paste("Distance = ", currentDistance, " feet"))
text(xTextValue, yTextValue-10, paste("Latency = ", round(Dtotal[index]/1000,0)," seconds"))
```
